### ISSUE TITLE
vmclient() messages in output, failing tests

### ISSUE THREAD

**Issue by lupinix** [olebole/iraf-v216#38]
Hi,

while rebasing my packaging from the latest snapshot with backported patches for architecture support to the current master, I ran into test failures due do additional messages in output like this one:
`vmclient (x_nttools.e): access ttranspose.in -> 1`

I get the same result with both Fedora 28 and Debian Stable, in attachment you'll find the build log (make linux64, make sysgen and output of run_tests script). Currently I'm investigating where the failures start, for sure the snapshot 2.16.1+2018.03.10 works fine.

Greetings,
Christian

Build log with commit hash (the commit from 9 May) [iraf-debian-stable-c2acbbb1b2b58bad645bf01aa256cd3dd3832964.log](https://github.com/olebole/iraf-v216/files/1994474/iraf-debian-stable-c2acbbb1b2b58bad645bf01aa256cd3dd3832964.log)

**Comment by olebole** [comment]
First guess: [`vmdebug`](https://github.com/olebole/iraf-v216/blob/c2acbbb1b2b58bad645bf01aa256cd3dd3832964/unix/os/zfiobf.c#L504-L506) is somehow switched on.

**Comment by olebole** [comment]
I test all versions with Ubuntu 12.04 and 16.04 (and with the current Debian testing), and never observed this. A test compilation with Debian Jessie also was successfull.

First guess: [`vm_debug`](https://github.com/olebole/iraf-v216/blob/c2acbbb1b2b58bad645bf01aa256cd3dd3832964/unix/os/zfiobf.c#L504-L506) is somehow switched on.

Which is something I don't understand: `vm_debug` is [static and initially set to `0`](https://github.com/olebole/iraf-v216/blob/c2acbbb1b2b58bad645bf01aa256cd3dd3832964/unix/os/zfiobf.c#L404). And is set to one (or another value) only if the environment variable `VMCLIENT` [contains the `debug` string](https://github.com/olebole/iraf-v216/blob/c2acbbb1b2b58bad645bf01aa256cd3dd3832964/unix/os/zfiobf.c#L708-L711).

Changes in `zfiobf.c` are:

* Add arguments to IRAF function declarations [`6b1567ba41`](https://github.com/olebole/iraf-v216/commit/6b1567ba41c7fb7f95996dcfca157016341f28ce#diff-e5d5a1b7d39b17f403c2d6758a08363f),
* Include header files instead of declaring libc functions locally [`eca754ee3c`](https://github.com/olebole/iraf-v216/commit/eca754ee3c93bfe90025f0d1183d417771eb960d#diff-e5d5a1b7d39b17f403c2d6758a08363f)

which both don't look very dangerous.

Could it be that by chance the `VMCLIENT` environment variable is set? For example, in a running VirtualBox? When I run 
```
$ VMCLIENT=debug ./test/run_tests
```

on my Jessie, I get the problem as well.

**Comment by olebole** [comment]
The build instructions are the usual
```
$ ./install [enter ...]
$ make linux64
$ make sysgen
$ ./test/run_tests
```

I still think it is somewhere in your environment. Maybe you point the debugger to [`vm_initialize()`](https://github.com/olebole/iraf-v216/blob/c2acbbb1b2b58bad645bf01aa256cd3dd3832964/unix/os/zfiobf.c#L671) and then check that `vm_debug` is set to zero, or whether it is then set in this function?

**Comment by lupinix** [comment]
Found the trigger: I used the github generated tar files for versions at special commit, e.g. https://github.com/olebole/iraf-v216/archive/c2acbbb1b2b58bad645bf01aa256cd3dd3832964.tar.gz

These have the long commit hash in the folder name, too long as it seems. If I rename it to e.g. iraf, everything is fine. This also explains why the tagged snapshots work, they have a much shorter name. There is no coincidence with/without virtualization, this was just a random fact as I used the git repo on the local machine while using the pregenerated tar in the virtual machines.

Result: There is some kind of issue with a too long path. Closing as I just use self generated tar files for Fedora packaging now with short name.
